### ISSUE TITLE
Mention incompatible Keyhive RGB fork in the documentation

### ISSUE THREAD

**Issue by josefadamcik** [josefadamcik/SofleKeyboard#105]
I have just learned that Keyhive is selling a modified version of Sofle RGB. Apparently they forked the design and changed the PCB to be non-reversible, it's apparent on the image from their build guide:  https://github.com/keyhive/build_guides/blob/master/docs/images/sofle-rgb/LED_order%5B1%5D.png

The way how they did that makes firmware incompatible with the version in this repository and may cause other confusion.

I will add:

- disclaimer to the RGB build guide and link to their build guide https://github.com/keyhive/build_guides/blob/master/docs/keyboards/sofle-rgb.md
- mention the version on the HP (again with disclaimer).

Maybe somewhere else, I'll think about it.

@DaneEvans maybe you already know about this, just making sure you are aware. I'll update the doucumentations etc.

**Comment by DaneEvans** [comment]
Thanks, I saw that it existed at some point I think when I was making the
V2, but I didn't go looking into their pinout to check the compatibility.

It's definitely worth mentioning, given that the same search strings will
end up in both places.
