### ISSUE TITLE
Help: LED still turns on after de-bridging the LED jumpers and disabling RGB in firmware?

### ISSUE THREAD

**Issue by codevogel** [josefadamcik/SofleKeyboard#114]
**Kind of issue?**
Bug / Assembly

**Which Board?**
RGB 

**Which Board Revision?**
v2.1

**What steps have you taken**
* [x] I have searched the Issues page
* [x] I have read the documentation 
* [x] For LED issues I have checked the following things 
        - the pro micro is programmed (and currently telling the LEDs to do something)
        - the pro micro is powered (and showing LEDs)
        - the LEDs are powered (check 5v across pins 1 and 3 of J1)
        - are any of the LEDs showing 

**What is the issue?**
I installed all of my LEDs on my Sofle, but found out that only one turned on. I had bridged all the jumpers to enable all the lighting features (per key, indicator and drop lighting).
Since I am a beginner at soldering, I don't want to bother with desoldering all the LEDs and troubleshooting why they all don't work (I probably burned a few of the mini LEDS).
Thus, I decided to ditch the LEDS alltogether, and just move on to actually building the keyboard.

I plan on leaving the not working LEDs in, but have them just do nothing. Since I'm not sure if they will cause any other issues, I wanted to disable them again through debridging the jumpers.

However, now that I unbridged the jumpers, the one single LED that was working earlier still lights up?
How can that be?
I will include photos showing the jumpers. I am pretty sure that I unbridged them all, right?

**What you expected:**

I thought the LEDS shouldn't light up at all if you dont bridge the jumpers? Why is one getting power?

**Photos for clarification**
j6 side 1: 
![image](https://user-images.githubusercontent.com/8700780/137495907-ad48fb06-7fb5-4ecd-baec-b1fef8191863.png)
j6 side 2:
![image](https://user-images.githubusercontent.com/8700780/137495965-ea2fa840-0e9c-4aa8-b638-d9e05e3dc656.png)

Backlight enable + Light select side 1:
![image](https://user-images.githubusercontent.com/8700780/137496343-ab641175-2564-48e2-a712-c8f83267b402.png)
Backlight enable + Light select side 2:
![image](https://user-images.githubusercontent.com/8700780/137496380-00583767-d722-4367-b28e-00d2f69e41d6.png)

Led still working:
![image](https://user-images.githubusercontent.com/8700780/137496411-985b5375-85b7-4ada-86ff-879d043a36f7.png)

**Comment by kemmel-dev** [comment]
Update: even if I flash software with `rules.mk` containing the line `RGBLIGHT_ENABLE = no` the led still powers on

**Comment by DaneEvans** [comment]
I can see from the pictures that you've absolutely cooked at least one of the LEDs. 
The cooked board around the headers is also worrying, turn the heat down on your iron, and use some flux. 

Sometimes a dry joint will cause the LED to turn on, but it shouldn't be repeatable, it's more likely that you've fried the control chip in a way that has left the green LED on. Put that LED face down on a thumb tack while heating up all 4 pads on the back, and it should pop right off as the board drops down to the table. 

If you want lighting, and your iron, or control is that bad, then I suggest a section of LED strip onto the header. Same effect, but you don't need the same soldering  ability. 

The LEDs will not cause any issues with any other function unless you short out the 5v lines.
