### ISSUE TITLE
Help: LEDs not working and Elite C status LED cuts out

### ISSUE THREAD

**Issue by bmosley** [josefadamcik/SofleKeyboard#117]
**Kind of issue?**
_Assembly / HELP!_

**Which Board?**
_RGB_

**Which Board Revision?**
2.1

**What steps have you taken**
* [x] I have searched the Issues page
* [x] I have read the documentation 
* [x] For LED issues I have checked the following things 
        - the pro micro is programmed (and currently telling the LEDs to do something)
        - the pro micro is powered (and showing LEDs)
        - the LEDs are powered (check 5v across pins 1 and 3 of J1)
        - are any of the LEDs showing 

**What is the issue?**
sofle_rev1_rgb_default from QMK's repo up to date and compiled okay.

I cant get any LEDs working at all (event the status indicator). I added sockets and have my elite C on right now but as soon as I plug in the USB the device is not showing up in either QMK after clicking reset on the pro or even status LED on the pro itself. This is the only build I havent gotten to work so puzzled as Ive tested the LEDs with a multimeter and get a solid output. No idea what to do next here. Any advice?

**What you expected:**

one of the images shows the Status LED on the back... ive removed that and put on the surface of the board instead. No difference.

![image0](https://user-images.githubusercontent.com/705077/138185995-c1c46597-3277-44f4-a1c5-4045ff520852.jpg)
![image0-1](https://user-images.githubusercontent.com/705077/138186003-3400d7a2-d5dc-418d-bca3-d129693db35e.jpg)
![image0-2](https://user-images.githubusercontent.com/705077/138186004-80678895-971b-438d-9e71-0fe3d9122377.jpg)

**Comment by bmosley** [comment]
strange the boxes show checked for me (thought I had to do it after the issue was create) sorry!

![Screen Shot 2021-10-20 at 18 06 53](https://user-images.githubusercontent.com/705077/138193133-18af75b6-0baf-4a08-bcde-c1b86af9b3da.jpg)


so yes, I think I was a bit unsure of the LED orientation from the docs. I assumed that the notch (DIN) for my LEDs was oriented in a way that it sits on the highlighted pad. I figured that maybe I had them reversed so flipped the indicator LED 180deg and removed the LED#2 entirely so there wouldn't be a short somewhere else down the line. the Elite C only shorts plugged in so something is clearly my fault there I just don't know where at this point

**Comment by STotev** [comment]
A little late answer to this but on the last picture, the indicator has the wrong orientation. The small dot should point to the side of the silkscreen. You need to flip it.

Also, if you are only checking that they are properly grounded and have 5V, it won't help much. You must ensure that you have something on the Dout pin because this will break the chain depending on what you have enabled.
