### ISSUE TITLE
Add a warning that sockets need to be in the right orientation

### ISSUE THREAD

**Issue by AlexDaniel** [josefadamcik/SofleKeyboard#12]
The build guide stresses that diodes should be in the right orientation:

> Starting with the diodes. They belong to the backside of the PCB. Make sure you have orientation right - they are all oriented to the same side.

However, it does not say anything about the orientation of sockets:

> Sockets for switches belong again on the back side, the same side as diodes. Make sure they are flush with PCB.

Of course, the sockets are drawn on the silkscreen so it should be hard to get it wrong… That being said, because of how nicely they snap into the board, it is easy to think that there is no wrong way to insert the sockets. Also, because it is a repetitive operation, it is probably possible to get just a few wrong.

Don't ask me [how I know](https://user-images.githubusercontent.com/5507503/92330354-d7781600-f076-11ea-8774-2a2e91f1eac2.jpg)! :facepalm: Fixing it requires [a jig](https://user-images.githubusercontent.com/5507503/92330367-f8d90200-f076-11ea-91a3-e14af6b241b9.jpg) to put light pressure through one of the holes while applying heat to the pads. Go slow and switch between the pads often. It will take an [an hour or so](https://user-images.githubusercontent.com/5507503/92330370-fc6c8900-f076-11ea-9749-aa50db0f22e6.jpg) to fix the whole board. Both the PCB and sockets can then be reused.

**Comment by josefadamcik** [comment]
@AlexDaniel ouch, painful mistake.

I'll update the guide and mention to pay attention to the orientation on silkscreen.
