### ISSUE TITLE
LEDs ?

### ISSUE THREAD

**Issue by chimuelo22** [josefadamcik/SofleKeyboard#14]
Hi there!
Did you included some LED in your board? Because I couldn't find nothing about that...I suppose I can add them, since it's very similar to Lily58... I saw there 3 connectors... But the question is to get your knowledge and opinion about that.
Thanks for the info!
Regards,
P

**Comment by josefadamcik** [comment]
@pp222 
I haven tried it but yes, the three pads are there as on Lilly58 and connected in same way. There's nothing in the firmware, though. Should be easy enough to add (qmk has some support) but I have never felt a need to have LEDs on my keyboard so I have never looked into details.
