### ISSUE TITLE
Gerber Version of Tenting Case for Sofle V2 and Sofle RGB

### ISSUE THREAD

**Issue by ghost** [josefadamcik/SofleKeyboard#151]
Laser cutting is sometimes not easy to find. It is also generally very very expensive, at least in my area. 

Could you create Gerber files for the top and bottom plates, so that we can print tenting case plates in FR-4 when ordering the PCB? 

I wonder if 1.6mm tenting case plates would be too thin or not. I think it would be fine, especially as long as we put spacers between the two halves to fill the gap. It would be very convenient to be able to buy the tenting cases with the PCB. 

From what I've read, I believe tenting is a very strong ergonomic addition to the keyboard. So much so, that I wouldn't buy a Sofle keyboard, or other ergonomic keyboard, without it. Making the tenting case more accessible by having Gerber files would be very important for me and probably others. 

I want to build a Sofle but this is what is holding me back. I would really appreciate Gerber Tenting Case files, and then I would be able to build a Sofle. There is a dxf already. I believe it can be as simple as converting it in KiCad or AutoDesk.

**Comment by josefadamcik** [comment]
Hi @Smitty-Werbenjagermenjensen , thanks for the suggestion!

There is one missing piece of information, you haven't mentioned which version of Sofle you are talking about. Is it for the RGB version?

From my side, I do not plan to do any adjustments to the tenting case and I would assume other maintainers might not be eager to do that as well. But contributions are always welcome! 

The tenting case (if I remember correctly) was submitted by a community member. I believe they might have been selling the case in their shop (sadly I do not remember any links or anything). So maybe you could try to google around, check Reddit etc. it might be possible to buy it somewhere.

> I wonder if 1.6mm tenting case plates would be too thin or not. I think it would be fine, especially as long as we put spacers between the two halves to fill the gap. It would be very convenient to be able to buy the tenting cases with the PCB.

People have most likely done that, but I personally have no experience with tenting. Maybe the best shot would be to test it.

**Comment by DaneEvans** [comment]
The RGB has it already, and has had since release
