### ISSUE TITLE
One column and one row suddenly not working

### ISSUE THREAD

**Issue by F1orian** [josefadamcik/SofleKeyboard#163]
Ijust fineshed building the RGB Version and tested all keys successfully before soldering the LEDs. Now I've soldered all the LEDs and everything seemed to work, but upon testing all the keys again, I was greeted with one dead row and one dead column. LEDs all still work.

![image](https://user-images.githubusercontent.com/27896106/194913282-6d338529-cf33-424b-b269-da38b2390490.png)

What could be the cause of this, and how do I troubleshoot this?
Thanks a lot in advance.

**Comment by DaneEvans** [comment]
Check that the switches are all plugged in properly.

Then look at the switch and diodes around the common key for both rows.
It's probably a bad diode. I think a shorting diode presents that way, I'd
need to check the schematic to be sure.

If you have them spare, it's probably easier to just replace both of them.

**Comment by F1orian** [comment]
Thanks for taking a look!

I've checked the schematic but I was unable to identify the diode(s) that I should replace. Also I'm a bit skeptical because they all worked before. Are they sensitive to heat, like the LEDs?

Looking at the schematic, I don't think there is a single diode that affects all switches of col2:
![image](https://user-images.githubusercontent.com/27896106/195568529-ce601ff4-e8eb-493b-8a94-4d3b9aa54fae.png)

There are however a few diodes in row0:
![image](https://user-images.githubusercontent.com/27896106/195568381-23d7ffac-f034-4dc5-a390-eef349ab59ba.png)


Sadly I have no experience at all when it comes to reading schematics, so if you could take another look at this, before I start de-soldering and potentially breaking something for real, I would really appreciate that!

**Comment by DaneEvans** [comment]
One other thing I'll note.  The highlighted row and column on your post are
adjacent pins at the micro end.  If you've been heavy handed with the
solder there could be a short there too.

If the columns get driven low when they aren't in use, then a simple short
between those, or of the common diode would probably cause all your
issues.  I can't recall if qmk does that, but I have a feeling it does.

Also looks like that screen shot is my board.  Why the hell did I length
match those traces?

**Comment by F1orian** [comment]
Alright, thanks a lot for your help so far! 
I'll get a multi-meter on the weekend and then I'll check the things you suggested.

I just did some cleaning-up on the pins at the micro on the PCB-side (quite sure there's nothing shorted on this side), and the pins for col2 and row0 on the micro itself. After that, col2 was working for around a minute, but weirdly it stopped working again. Row0 remained unchanged.

**Comment by DaneEvans** [comment]
In that case I'd say 2 problems.
One is a loose pin or dry solder joint at the microcontroller on that
column.  It worked for a while after you made it connect as you poked at
it.

If you're using sockets, that leg may be too short.


But yeah, a metre is pretty much the minimum trouble shooting gear you
need.

**Comment by F1orian** [comment]
So I got the metre and did some testing: 

**Row0**
I have continuity to gnd on all switches (including row0) **except for col2**
Does that mean that row0 is just not connected to the micro correctly but everything else in the chain is soldered correctly and working?

**Col2**
I have continuity on col2 to the pin that connects to the micro for all switches of col2.

I am not quite sure how to proceed with these findings...

What options does that leave me with, also considering that col2 was briefly working for around a minute?
