### ISSUE TITLE
Building my first Keybaord, everything seems to be working except backlight

### ISSUE THREAD

**Issue by tomdcpennington** [josefadamcik/SofleKeyboard#164]
**Kind of issue?**
Both halves of the board, when connected together or not show oleds, indicators and drop lighting. But none of the per key leds light up.

**Which Board?**
The RGB not Keehive version. Running RGB_default keymap on both controllers

**Which Board Revision?**
RGB 2.1

**What steps have you taken**
* [Y] I have searched the Issues page
* [Y] I have read the documentation 
* [Y] For LED issues I have checked the following things 
        - the pro micro is programmed (and currently telling the LEDs to do something)
        - the pro micro is powered (and showing LEDs)
        - the LEDs are powered (check 5v across pins 1 and 3 of J1)
        - are any of the LEDs showing 
* Check solder on first LED in the chain by the jumper. Both sides seem fine.

**What is the issue?**
Per key LEDs not lighting. Nothing else seems to be having an issue. I don't have switches in currently and I have bridged 'Backlight enable' on ENA on the back of both sides of the board.

**What you expected:**
Expect per leds to light up. I expected at least a few to light up before the chain was perhaps broken, but the fact that none light up on either side of the board makes me think its not down to soldering but something else.

**Comment by DaneEvans** [comment]
Try the key command for RGB enable.
And brightness up.

Have you tried plugging the second half in directly? Any change?

If your enable bridge is setup properly, then it seems more likely to be
firmware and settings than soldering on the first LED of both boards.l at
the same time
