### ISSUE TITLE
Make the orientation of the Pro Micro explicit in the build guide/log

### ISSUE THREAD

**Issue by mehmetalianil** [josefadamcik/SofleKeyboard#17]
It is my first build, and I am used to mounting modules chip side up in other projects. Therefore I mounted pro micro that way, therefore swapped 5V and GND. I was able to program but of course bricked the OLED. 

It is hard to indicate it on silkscreen but i think there could be a warning or at least an image on the build guide that shows the correct orientation of pro micro. 

P.S. it was really painful to desolder 14x2? module with my geared towards SMT components.

**Comment by AlexDaniel** [comment]
I think I mentioned it elsewhere but yes, I did the same mistake. Didn't burn anything because I think I realized it earlier, but yeah.
