### ISSUE TITLE
A link in Sofle Choc build doc is not available

### ISSUE THREAD

**Issue by Ross-Li** [josefadamcik/SofleKeyboard#172]
Link in this doc https://github.com/josefadamcik/SofleKeyboard/blob/master/docs/build_guide_choc.md

at line:
+ Make sure your QMK environment [is setup](https://beta.docs.qmk.fm/newbs/newbs_getting_started).

is not available. Here is the error message when opened:
![image](https://user-images.githubusercontent.com/61273074/215941508-15a48da3-60c1-43f3-a836-a66a545f75db.png)

Possible updated link of qmk "getting started" guide is:
https://docs.qmk.fm/#/newbs_building_firmware_configurator

(Sorry to submit this in the software bug issue section, as I can't find a documentation issue issue section.)

**Comment by JellyTitan** [comment]
Submitted PR to fix: https://github.com/josefadamcik/SofleKeyboard/pull/176

**Comment by DaneEvans** [comment]
Closed, as it got merged
