### ISSUE TITLE
SW: summarise your issue here.

### ISSUE THREAD

**Issue by MartinLyne** [josefadamcik/SofleKeyboard#193]
**Which Board?**
RGB Board v2.1

**Which Board Revision?**
_This is the one written on main pcb that you are using. 
RGB =  2.1

**What Software are you using?**
QMK, modified rgb_default

**What is the issue?**
I don't know if this is just me or not, but I have my keyboard setup (physically) with indicators+per-key+underlights and regardless of which RGBLED_NUM and RGBLED_SPLIT values I use I still have 6 per-key LEDs stuck on Red. This is the same on both boards, so I assume it is software related.

I've changed the values to 78+39/39, 72+36/36 and various other combinations. 

If I use RGBLIGHT_EFFECT_RGB_TEST it is the same. 

More info: The indicator light is red, underlights are all red
using the RGB+underlight+indicator images in the build guide these are LEDs 8, 9, 10, 11, 26 and 27

**What you expected:**

* All per-key LEDs to perform the selected light effect
* Some indication in build guide what the firmware values should be set to for the various underlight/per-key/indicator configurations

Thanks for any help!

**Comment by DaneEvans** [comment]
At a guess, you have layer lights set. Find whatever sets things to red, and remove it in the config.

**Comment by MartinLyne** [comment]
> At a guess, you have layer lights set. Find whatever sets things to red, and remove it in the config.

Sorry this is just basic firmware, I've not modified anything. I have no idea how to set light colours outside of the presets.

Using the firmware as is should just work when you have all lights enabled is my expectation.

**Comment by DaneEvans** [comment]
Then I suggest that you tell us which keymap you are using.  But the short
answer is no.

The default (qmk) that I created includes demos of a bunch of functions,
including later indicators, probably a numpad backlight etc.  It is there
to be modified.

And then there are a bunch of other 'defaults' that I have no idea what or
where they are from (via, several others) that supposedly make things
simpler, but really just prevent there from being a source of truth
