### ISSUE TITLE
Add VIA support for Sofle Choc

### ISSUE THREAD

**Issue by JellyTitan** [josefadamcik/SofleKeyboard#194]
I'd like to add VIA support for the Sofle Choc.
Since there's already a via folder on the QMK side, the config on the VIA side needs to be added.
I didn't see any open PR's, so I went ahead and submitted one for the Sofle Choc: https://github.com/the-via/keyboards/pull/2139
All PR's are paused on VIA for December/January, so it'll sit for a bit.

**Comment by JellyTitan** [comment]
The VIA PR is [blocked ](https://github.com/the-via/keyboards/pull/2139#discussion_r1477167695) because in the QMK branch the Product ID and the VendorID are the savme as the Sofle rev1.
![image](https://github.com/josefadamcik/SofleKeyboard/assets/72168556/e9279941-4217-4fe0-9c43-8e6ef4561064)

**Comment by brianlow** [comment]
@JellyTitan go for it!

**Comment by JellyTitan** [comment]
The PR for the vid/pid choc was closed and moved to a new PR. (Same code).
https://github.com/qmk/qmk_firmware/pull/24030

**Comment by JellyTitan** [comment]
@brianlow The PR to make the [Sofle Choc VID/PID unique](https://github.com/qmk/qmk_firmware/pull/24030) has been approved and merged into QMK master. The VIA PR has been updated.

**Comment by brianlow** [comment]
Great, let me know if you need anything

**Comment by JellyTitan** [comment]
VIA support has been [approved and merged](https://github.com/qmk/qmk_firmware/pull/24030). @brianlow is documentation support warranted?

**Comment by brianlow** [comment]
Up to you
