### ISSUE TITLE
Enhance: Provide Wiring Diagram

### ISSUE THREAD

**Issue by that-ambuj** [josefadamcik/SofleKeyboard#198]
**What feature would you like to see?**

I would like to get the wiring diagram for the keyboard. So that I can handwire my build. I'm pretty new to DIY keyboards and I want this to be my first attempt. I wanted to build something https://github.com/abstracthat/dactyl-manuform but It's too much to get started but I liked how they gave a good wiring diagram in the form of image to help people with hand wiring their builds. I'm on a budget, so I'm skipping the PCB on this build.

**Are you prepared to help?** 

Not yet, I'm a beginner.

**Comment by DaneEvans** [comment]
That already exists as a single source of truth in the schematics. 
Adding redundant documentation just causes more issues.
