### ISSUE TITLE
Does solfe RGB can control individual Key led color?

### ISSUE THREAD

**Issue by rajhlinux** [josefadamcik/SofleKeyboard#27]
I see that the solfe keyboard project has a RGB section.

Can the RGB solfe Keyboard control individual key led color?

Thanks

**Comment by josefadamcik** [comment]
According to the build guide it has per key LEDs, they are SK2812 which means they can be addressed individually. So from tho HW point of view it should be supported. I have no experience with pes key LEDs on keyboards, but I guess QMK Firmware supports per-key LED.

**Comment by rajhlinux** [comment]
Thanks for the helpful reply. That is good stuff :)
    On Monday, January 25, 2021, 07:52:00 AM EST, Josef Adamčík <notifications@github.com> wrote:  
 
 


According to the build guide it has per key LEDs, they are SK2812 which means they can be addressed individually. So from tho HW point of view it should be supported. I have no experience with pes key LEDs on keyboards, but I guess QMK Firmware supports per-key LED.
