### ISSUE TITLE
Using the right micro USB port instead of the magnetic left one

### ISSUE THREAD

**Issue by Parx8** [josefadamcik/SofleKeyboard#29]
Hi Josef, I would really like to know if there's a way to use the right micro USB port instead of the magnetic left one for the Sofle keyboard. Just really curious.

**Comment by josefadamcik** [comment]
Hi, there's, you can set it in the qmk firmware in several ways. Now it's fixed to MASTER_LEFT, you can either change it or use another apporach, see https://beta.docs.qmk.fm/using-qmk/hardware-features/feature_split_keyboard#setting-handedness
