### ISSUE TITLE
Inverted silkscreen?

### ISSUE THREAD

**Issue by AlexDaniel** [josefadamcik/SofleKeyboard#3]
What about inverting the silkscreen on most of the PCBs? Like [here](http://ncmachineworks.ca/wp-content/uploads/2014/01/PC280491.jpg). It adds an extra layer and makes PCBs feel nicer. Also, with some fabs there is a cost for non-green PCBs, but the silkscreen fill esentially makes them white. I'm personally interested in black boards, but black soldermask from JLCPCB feels junky so I want to try my luck with white PCBs and inverted silkscreen (which should be black).

**Comment by josefadamcik** [comment]
@AlexDaniel it might be interesting visually, but is there a way how to do it easily without loosing the ability to change the PCB design easily? Personally I have never tried to invert silkscreen so I don't know what are the options.

For me it sounds more like some kind of post-processing step: take exported Gerbers and run both silkscreen layers through some kind of inverting script.

**Comment by AlexDaniel** [comment]
> easily

Well, maybe not as easy. But you can have text and other stuff on ECO layers, and then subtract it in gerbers. Maybe [this](https://forum.kicad.info/t/negative-silkscreen/11849/3) is a good start.

Another option is to have silkscreen artwork in SVG and then just import it into KiCad. It requires an extra step to bring in the updates but it's not too bad.

**Comment by josefadamcik** [comment]
> > easily
> 
> Well, maybe not as easy. But you can have text and other stuff on ECO layers, and then subtract it in gerbers. Maybe [this](https://forum.kicad.info/t/negative-silkscreen/11849/3) is a good start.

Thanks for the link, it's interesting. But sadly not really practical way. The text is not the only thing on silkscreen. There are also symbols which are part of the footprints and that would be the more difficult part I would say. And they even have to use external script: gerber_combine -> i think something like that is more what you need - have a way how to say negate my silkscreen (which is something like substract it from something which is completely filled in so it might be possible to abuse gerber_combine for that purpose). 


>
> Another option is to have silkscreen artwork in SVG and then just import it into KiCad. It requires an extra step to bring in the updates but it's not too bad.

I would do that if there actually was some artwork I would care about. I have done some things  by combining SVG made in inkscape and KiCad (and importing/exporting things in both directions) ant it is indeed powerful approach. But it's also a lot of overhead. Doing it just to invert silk screen is too "expensive". I would prefer automated way that allows me to keep the project maintainable.

Also, I am quite sure it doesn't really make sense to have this as default - all my Sofle builds are made with white soldermask and black silkscreen and they look pretty good. I had Corne made with black-matte silkscreen from JLCPCB and it looked also very good (the only problem I had was that it was almost impossible to clean it nicely after soldering, at least I didn't find a reasonable way). Of course, this is highly subjective but there are plenty of people who might not like inverted silkscreen.

What I am trying to say here is: of course I am sure it's possible to do and of course I would be able to figure out why if I really wanted to. But for me this is something that you could do before you order PCBs yourself and doesn't have to be part of the repository. And if it was part of the repository it should a an optional post-processing step - e.g. a python script which would process the gerbers to make the change.

**Comment by AlexDaniel** [comment]
> There are also symbols which are part of the footprints and that would be the more difficult part I would say

Any reason you can't move them to another layer? If it's just text, then right click on the text, Properties, Layer → Eco1.user. If it's part of the footprint, then Ctrl+E to edit it in the footprint editor.

However, I agree, it should be other way around. We should draw the silkscreen fill on the eco layer and then subtract the normal silkscreen from it.

> all my Sofle builds are made with white soldermask and black silkscreen and they look pretty good

That's alright aesthetically, but white color is perhaps the least functional for keyboards because of the grime and stuff.

Anyway I'll take a look on how to achieve it in the easiest way before making my order, and I'll submit a PR with instructions or scripts.

**Comment by AlexDaniel** [comment]
If anybody is interested, I made an order for white boards with inverted silkscreen. I'll describe the process in a bit more detail later if the boards are fine.

**Comment by joaommartins** [comment]
> If anybody is interested, I made an order for white boards with inverted black silkscreen. I'll describe the process in a bit more detail later if the boards are fine.

I'm interested since I intend to order from JLCPCB and it's my first time ordering pcbs at all.

**Comment by AlexDaniel** [comment]
@joaommartins I hope you can wait a little bit. My boards were manufactured on 2020-08-16 but I chose the cheapest delivery option. The boards have various improvements to them, not just inverted silkscreen (something I intend to report as bugs soon). That said, I won't be sharing any files until I actually get the physical boards. I looked at the production files and JLCPCB did some undesired changes to the gerbers, especially the silkscreen. When I asked them not to do it they didn't really understand what I was trying to say… So I have to see how the boards turned out before I can recommend anything :)

**Comment by joaommartins** [comment]
@AlexDaniel Not a problem at all, I'll be keeping an eye on this repo and learning about pcb manufacture meanwhile.

**Comment by AlexDaniel** [comment]
They arrived! Looks pretty good to me, I'll explain the process in detail a bit later and also show some photos.

**Comment by AlexDaniel** [comment]
OK, here are most of the details for making boards with inverted silkscreen.

Let's say you wanted to have a solid board (like the bottom plate) with silkscreen across the whole board, with no markings or logos (just solid silkscreen fill). Can you just cover the whole board with a polygon on the silkscreen layer? Like this:

![image](https://user-images.githubusercontent.com/5507503/91581116-b87ed300-e956-11ea-9476-ab4708ca0941.png)

The answer is yes, but with two caveats.

### 1. Pads
If you have any pads, most manufacturers will remove silkscreen from them. However, it is not guaranteed, as demonstrated by this famous case:
![silkscreen on pads](https://i.imgur.com/athrLYk.jpg)
([source](https://www.eevblog.com/forum/projects/silk-screen-on-exposed-pcb-pads/))

KiCad allows to “exclude pads from silkscreen” when you generate the gerbers, and you probably want to make sure that the checkbox is checked:
![image](https://user-images.githubusercontent.com/5507503/91581562-3cd15600-e957-11ea-93d0-668d5ea994e7.png)
There is also a “Subtract soldermask from silkscreen” option but I personally think it is too much. It will create holes for pads that are even bigger, but due to silkscreen misalignment it can expose some of soldermask too.

### 2. Edge cuts 
If you make your silkscreen exactly the same size as your board, keep in mind that the silkscreen is the most imprecise part of your boards. Usually, the silkscreen layer will be misaligned at least a bit, if not a lot. This means that your silkscreen polygon will be shifted, revealing soldermask on the edges of your board. Here's an example:
![silkscreen_shinethrough](https://user-images.githubusercontent.com/5507503/91582442-7f476280-e958-11ea-8ed6-d2eca17456d8.jpg)
(boards for [one of my older projects](https://progarm.org/))

On the image above you can see green soldermask being visible on the left side but not on the right side, that is because of the silkscreen misalignment. The solution to that is to make sure your silkscreen overlaps the board edge, this way the mill will go through your silkscreen when cutting the board edge leaving no visible soldermask. However, this didn't really work for my JLCPCB order, and this is what they did for the production files:
![2020-08-06-181526_1366x768_scrot](https://user-images.githubusercontent.com/5507503/91582883-1e6c5a00-e959-11ea-87ef-dff07e38ae1e.png)
(This is the screenshot that I was using when I was trying to explain the issue to JLCPCB, they still didn't get it though. The image on the right is the original gerber file, the image on the left is their production files. The arrow shows what you should want your gerber files to be, but the sad reality is backwards :) )

Notice that not only did they cut the silkscreen layer based on the outline, but they also made sure that it is inset by a small amount. That is, when ordering from JLCPCB, *you will always have a soldermask outline near all of the board edges*. This is how it looks like:
![20200828_153440_960627659](https://user-images.githubusercontent.com/5507503/91583111-65f2e600-e959-11ea-9bdc-86bfc96c965d.jpg)

Notice that there is a white outline near all of the board edges.

When I asked JLCPCB not to do that they didn't really understand my request. I think it's much easier to embrace this limitation – just add an intentional 1mm-1.5mm silkscreen outline for all of your edge cuts. It will add contrast, making the board look more stylish.

### How to invert the silkscreen

Now, the process for inverting the silkscreen can be different depending on what exactly you want to achieve. For the top and bottom plates it is sufficient to simply add a polygon on silkscreen layers that covers the whole board. This is what I did, because I didn't want to have any graphics there anyway. You may choose to do it differently.

For the main board, however, I still wanted to have normal silkscreen markings for the components. So here is the process:
1. Generate gerbers with your normal silkscreen. Rename your silkscreen gerber files so that you know that this is the original silkscreen.
2. Add a polygon to silkscreen layers that covers the whole board. Generate the gerbers again.
3. Download [kicad-utils](https://github.com/bobc/kicad-utils) and use the [gerber_combine.py](https://github.com/bobc/kicad-utils/blob/v5/scripts/gerber_combine/gerber_combine.py) script to subtract one gerber file from the other. The result would be your final gerber file. Repeat for both layers! Unfortunately, `gerber_combine.py` script is somewhat broken, so you might need to modify it to get it working.

I went through a slightly more difficult process because I wanted to have “JLCJLCJLCJLC” string on the board. I don't know if they are able to invert the board number, so I did the following
1. I added a solid rectangle polygon to the normal silkscreen layer. This will later form a hole for our silkscreen text. Then I generated the gerbers like normally.
2. Same as described previously for Step 2, I generated silkscreen layers that cover the whole board.
3. I added “JLCJLCJLCJLC” string to one of the unused layers (in this case Margin layer). You can do this step later or ahead of time, it doesn't matter that much. The result should look like this:
![image](https://user-images.githubusercontent.com/5507503/91607547-b7609c80-e97c-11ea-9046-53ff8f6e8a91.png)
4. Take your filled gerber file and *subtract* normal silkscreen from it, then *add* the Margin layer. It may sound complicated but it is actually very easy once you understand the order of operations. Your silkscreen will then look like this:
![image](https://user-images.githubusercontent.com/5507503/91607710-04447300-e97d-11ea-9030-4a436bc18027.png)
And, once manufactured, like this:
![JLCJLCJLCJLC](https://user-images.githubusercontent.com/5507503/91608542-6e114c80-e97e-11ea-9b87-acdc2aec85e9.jpg)



### Some other interesting details

JLCPCB will drill into the edges of square holes like this:
![image](https://user-images.githubusercontent.com/5507503/91583595-1fea5200-e95a-11ea-9300-bf5a42dd6a60.png)

It makes sense because the inner corners can't be square, but notice that it also cuts into the copper and silkscreen around the hole and adds a 0.02mm artefact. I can't see it with my eyes so it's nothing to worry about, but maybe it means that the gerbers should include drill points on the corners right from the start.

JLCPCB also modifies overlapping holes so that one of them is milled like an edge cut instead:
![image](https://user-images.githubusercontent.com/5507503/91584001-ab63e300-e95a-11ea-9a3d-4b8bda7eaa5f.png)

That said, the smaller holes were left untouched. The holes did end up being more or less oval-shaped, meaning that their machines did indeed attempt to drill them. I don't understand how it can possibly work, because the drill is mostly going through an empty hole and not engaging with the board fully. Maybe the broken drill bits are included in the price? :P

### Results

Here are the boards:
![boards1](https://user-images.githubusercontent.com/5507503/91606131-36a0a100-e97a-11ea-8d99-5b1d79a7907d.jpg)
![boards2](https://user-images.githubusercontent.com/5507503/91606137-3902fb00-e97a-11ea-98e0-fdb4089505c0.jpg)

They are OK, I'm very satisfied! Some things can be improved, of course.

The interesting part is that the silkscreen is not entirely flat but has a certain texture to it. Obviously, it is a manufacturing flaw. I am actually liking it a lot. All of the lines are parallel, they look like an intentional fake wood texture that is sometimes put on furniture. Here are some images so that you can see it better:

![silkscreen-texture](https://user-images.githubusercontent.com/5507503/91606530-e37b1e00-e97a-11ea-8c27-b0f590208ef7.jpg)
![silkscreen-texture2](https://user-images.githubusercontent.com/5507503/91606535-e5dd7800-e97a-11ea-80c9-c4070cdf91a0.jpg)


You may be wondering if inverted silkscreen is worth the trouble when you can just order pcbs with black soldermask. Yes, it is worth it! Here's the comparison:
![silkscreen_comparison](https://user-images.githubusercontent.com/5507503/91605685-8763ca00-e979-11ea-9270-999d577777ba.jpg)
(boards for two of my projects: [RoboRG](https://github.com/RGVID-EU/RoboRG-EDA) and [Butterboard](https://github.com/RGVID-EU/Butterboard))

Black soldermask from jlcpcb is matte, but it feels rough to the touch (sandpaper-like feeling) and it looks thin and cheap. In comparison, black silkscreen is a very smooth and thick layer that feels nice.

### My modified gerbers

If you want to use my gerbers to make an order, here is a gist that you can download: https://gist.github.com/AlexDaniel/72cb48b41fc0140e91b529a5ce0060a0

But I have to note that these issues are present:
* [Silkscreen lines are a bit too thin](https://github.com/josefadamcik/SofleKeyboard/issues/11)
* [Impossible holes](https://github.com/josefadamcik/SofleKeyboard/issues/9)
* The main board has a “JLCJLCJLCJLC” string on the silkscreen layer so that you can save some money when ordering from JLCPCB (choose “Specify a location” in “Remove Order Number”). If you don't want to order from JLCPCB then you definitely want to change that.
* The gerbers have no cute Sofle logo or any other identifying elements. To bring it back you'd have to use `gerber_combine.py` and follow the process above. My equipment usually gets taped over anyway (for reasons similar to the ones [mentioned here](https://youtu.be/K9fQn1bQVsQ?t=214)), so I didn't bother.

Also, compared to the last Sofle release, these issues were fixed:
* [One of the holes (pads) on the top plate is different](https://github.com/josefadamcik/SofleKeyboard/issues/7)
* [Silkscreen error (R1/R2)](https://github.com/josefadamcik/SofleKeyboard/issues/5)
* [Missing silkscreen markings](https://github.com/josefadamcik/SofleKeyboard/issues/6)
* [Acute angles on copper layers](https://github.com/josefadamcik/SofleKeyboard/issues/8)


I think that's about it. Please let me know if there's anything I can help with.

Please feel free to close this issue because I solved the problem for myself. :) I hope my instructions are detailed enough for others to achieve something similar.

**Comment by josefadamcik** [comment]
@AlexDaniel Thank you very much for taking the time to write this down and also to create issues for all the problems with the design you have noticed. I think I'll create a small section in the documentation (something like "Modifications") and link this issue & your comment from it so people can find it if they prefer inverted silk-screen. 

To the bugs: I'll leave them (at least most of them) here among issues open, but I am most likely not going to fix them in the first version of the design. But it's great feedback and I'll make sure the next versions doesn't have the same problems (at least in the cases where I would be able to find the solution). Thanks again.

**Comment by AlexDaniel** [comment]
@josefadamcik thank you for a great project! The documentation is very nice!

**Comment by olDirdey** [comment]
@AlexDaniel can you explain what you have changed in the gerber combine scrypt? in my output the silkscreen looks exactly the same as before, nothing is deducted after the script has run

**Comment by AlexDaniel** [comment]
@olDirdey if I remember right, there were some obvious python errors, probably because the script is rather old. The script is written in python2 which isn't even easy to install nowadays. But, if you're able to run it without errors, then you're good!

How are you running it? Are you providing two files? Are you using the `-s` flag?

**Comment by olDirdey** [comment]
@AlexDaniel thanks for the feedback. unfortunately I have no knowledge of python to find an obvious error. I use the command "python gerber_combine.py full.gbr -s text.gbr -o final.gbr" full is my filled area and text.gbr is the text i want to subtract from it. but the output file is the same as the file with the full area

**Comment by AlexDaniel** [comment]
Based on the command history, I see that I was using this command:
```
./gerber_combine.py -s silkscreen-magic/SofleKeyboard-B_SilkS_FULL.gbo silkscreen-magic/SofleKeyboard-B_SilkS.gbo
```
I don't know if the order of arguments is important, but that's something to try. If you don't see any errors, then I think the script is fine.

**Comment by olDirdey** [comment]
thanks again. I will try a little bit
