### ISSUE TITLE
Wrong hole on the corner?

### ISSUE THREAD

**Issue by BeTmAsTeR** [josefadamcik/SofleKeyboard#34]
I know nothing about pcb design so i'm just reporting an issue that JLCPCB faced and kindly reported back to me.

I sent JLCPCB the gerber files for v2 and they sent me this mail

> As shown below, do you need to cut out the circle at the arrow on PCB? It is in KO layer.
> 
> 
> Or we can delete it to proceed?
![627342bf6d72445d9fb6ecdf4e04789e](https://user-images.githubusercontent.com/761740/106882192-c17e8800-66de-11eb-9c6e-dd11b3542d65.png)

Is this an issue?

**Comment by josefadamcik** [comment]
Hi Matteo, thanks for letting me know.

They can delete it and proceed.

I'll check the gerber's again to fix them, not really sure what happened
there.

Best regards,
Josef

**Comment by josefadamcik** [comment]
Fixed int the KiCad files, gerber files and crated a new version with fixed files at https://github.com/josefadamcik/SofleKeyboard/releases/tag/v2.0.1
