### ISSUE TITLE
Sofle RGB has an unconnected via for NET34. Underlight LED circuit.

### ISSUE THREAD

**Issue by jmo808** [josefadamcik/SofleKeyboard#38]
I temporarily worked around the issue by scratching the soldermask off and globbing some solder. I will submit a PR in the next few days.

**Comment by DaneEvans** [comment]
That's a weird one.

Thanks for the quick turnaround, hopefully doesn't catch anyone else out, I
know there are a few people looking at making one.

I'll check it out tomorrow probably, if you haven't submitted one by then.

**Comment by jmo808** [comment]
Here's some pics as an FYI. 
![image](https://user-images.githubusercontent.com/6784537/107595551-96160480-6bda-11eb-91e7-d9e6e01b52c9.png)
![image](https://user-images.githubusercontent.com/6784537/107595560-9ca47c00-6bda-11eb-9221-d529cebfdf93.png)
Second pic has where the missing trace was circled in red. It's an easy fix in KiCad

**Comment by jmo808** [comment]
I finished building both sides of the keyboard and have verified that this fix does indeed work. So I will submit the PR soon.

**Comment by tiadobatima** [comment]
Howdy... I'm wondering if this PR has been merged? I gave a quick look and didn't see any merges related to that in the last few days, but I could have missed something. I'm gonna wait for it before ordering :)
And thanks for the fix! ❤️

**Comment by josefadamcik** [comment]
> Howdy... I'm wondering if this PR has been merged? I gave a quick look and didn't see any merges related to that in the last few days, but I could have missed something. I'm gonna wait for it before ordering :)
> And thanks for the fix! ❤️

Hi @tiadobatima, there has been no PR opened yet.

**Comment by jmo808** [comment]
Sorry for the delay, I have gotten busy with work and haven't had the chance to submit this PR. I still need to load the JLCPCB DRC rules into KiCad and export the gerber. I'm also working on another PR for a 3d printed high profile case.

**Comment by tiadobatima** [comment]
I'm so sorry... I didn't mean to put any pressure. I know everyone is busy. I just wanted to make sure I didn't miss the boat :)
Thank you again for doing this!

**Comment by DaneEvans** [comment]
I'm in the same boat, work has been absolutely hectic.

I'm hoping to get one out this weekend. And update the documentation to
mention the issue in the R1 boards.

**Comment by DaneEvans** [comment]
I've submitted a merge request with a new version of the board, and updated the documentation. 

@tiadobatima, wait a day or so for Josef to accept it, or you can pull it from my repo. 

Thanks jmo for finding (and immediately solving) the issue - My apologies for the hassle, I never made the 2.0 boards, they just fixed a few issues I had in 1.0, and somehow I missed a missing net in the DRC.  How I have no idea, because I now I ran the checks, and it showed up as son as I ran them to start the fix.
