### ISSUE TITLE
RGB build guide typo?

### ISSUE THREAD

**Issue by rhscdn** [josefadamcik/SofleKeyboard#43]
The RGB build guide refers to a "SK2812" LED. Can you confirm this isn't a typo? There's the well loved WS2812 (which are big 5x5mm RGB LEDs), and variations which use the same protocol: SK6812, SK6812mini, SK6812mini-e. - The different variations have different pinouts. Wouldn't the 3.5x3.5mm RGB LEDS would be SK6812mini? Alternatively, do you happen to know a current aliexpress link for the needed LED?

**Comment by josefadamcik** [comment]
@rhscdn That's for sure a type but I think we already had the issue but apparently we didn't mange to fix all instances. Your guess is correct, it is SK6812 mini . I'll fix it in a moment.
