### ISSUE TITLE
Silkscreen error (R1/R2)

### ISSUE THREAD

**Issue by AlexDaniel** [josefadamcik/SofleKeyboard#5]
When looking at R1 and R2 resistors on the bottom of the board, you will see this on the silkscreen:

![image](https://user-images.githubusercontent.com/5507503/91502561-07822500-e8d1-11ea-9f05-a53b047eb5ab.png)

Pay attention to the resistor at the top. Is it “1” or “2”? It is actually both, a twone!

This is not just a rendering glitch. You can actually see it on one of the photos on the website:

![image](https://user-images.githubusercontent.com/5507503/91502720-6d6eac80-e8d1-11ea-9b31-a51c977f72c0.png)

There are two text fields on top of each other (on the same B.SilkS layer).

**Comment by DaneEvans** [comment]
Still present in the files, but we've moved on to v2 now. Won't Fix
