### ISSUE TITLE
Can't load footprints

### ISSUE THREAD

**Issue by joecabezas** [josefadamcik/SofleKeyboard#51]
how can I fix this?, it seems like there are absolute references to a path only the author have, how can we fix this?, or can those footprint be included in the repo?, thanks

![image](https://user-images.githubusercontent.com/110182/111732165-355d9580-8832-11eb-8126-ecdca0cde61e.png)

**Comment by josefadamcik** [comment]
All the footprints should be in the repository under footprints. Even the Keebio-Parts are included (as a git submodule, I believe). So just make sure they are properly checked out and change paths in the KiCad footprint library.

To be honest, you might not even need it unless you change something. But I am far from being a KiCad guru.

**Comment by joecabezas** [comment]
thanks, I just noticed that, thank you, I am closing this
