### ISSUE TITLE
Wrong link to QMK guide

### ISSUE THREAD

**Issue by josefadamcik** [josefadamcik/SofleKeyboard#52]
From a twitter message:

> Hey, Just to let you know on your build guide the Link to the QMK getting started guide doesn't work any more, the correct link is:
> 
> https://beta.docs.qmk.fm/tutorial/newbs_getting_started
> 
> Not
> 
> https://beta.docs.qmk.fm/newbs/newbs_getting_started
>

**Comment by DaneEvans** [comment]
You seem to have a few issues in the footnotes there .... 

![image](https://user-images.githubusercontent.com/22091505/113858462-1de94b00-97e7-11eb-8596-5d029c25ef0c.png)
