### ISSUE TITLE
Not routed trace?

### ISSUE THREAD

**Issue by joecabezas** [josefadamcik/SofleKeyboard#53]
Hello, thank you for this project, I am not a kicad guru but I found this, what is it?

![image](https://user-images.githubusercontent.com/110182/111763785-c1d27d00-885f-11eb-8e60-8177bedf836b.png)

is an unrouted trace between 2 vias?, shall be fixed?, thanks

**Comment by DaneEvans** [comment]
It's a pair of vias that were put in to join two ground pours. They look
connected to me, but try repouring them if it worries you, but it won't
have any detrimental effect.

  For some reason one of the pours has probably shifted, or the net
allocated to the vias has changed from gnd.

**Comment by joecabezas** [comment]
thank you, will repour, I am closing this
