### ISSUE TITLE
Sofle-RGB BG - LED table is wrong 

### ISSUE THREAD

**Issue by DaneEvans** [josefadamcik/SofleKeyboard#59]
**What is the issue?**
The LED select table in the build guide is wrong - at least column 1, 

Bypassing the indicator is 1-2 as per the silk screen and the diagrams higher up the page 

**What you expected:**
Consistency

**Comment by DaneEvans** [comment]
can be closed with #60

**Comment by josefadamcik** [comment]
Thank you for all the contributions 👍
