### ISSUE TITLE
One of the holes (pads) on the top plate is different

### ISSUE THREAD

**Issue by AlexDaniel** [josefadamcik/SofleKeyboard#7]
See this screenshot:

![image](https://user-images.githubusercontent.com/5507503/91503451-2aadd400-e8d3-11ea-9597-bfcbaf8296b3.png)

You can see that one of the holes is different.

Size X: 5mm, Hose size X: 2.2mm
vs
Size X: 4mm, Hose size X: 2.2mm

That is, the difference shouldn't really matter that much because the hole size is correct (it's just the pad that is different). However, I don't think this was intentional so it should probably be fixed.

**Comment by DaneEvans** [comment]
Fixed in the move to v2, as far as I am aware all of the case plates are cross compatible anyway
