### ISSUE TITLE
Spacers and screws for rgb

### ISSUE THREAD

**Issue by fabioluciano** [josefadamcik/SofleKeyboard#76]
Anyone knows which millimeter I need for spacers and screws?

**Comment by mvk15** [comment]
The same as for Sofle non RGB. For MX switches - 7mm. According to author of Sofle - Josef Adamčík, it can be 6mm. I have ordered 6mm and 7mm. Actually, the distance between the bottom side of the top plate to the top side of the bottom plate for me something about 6.25-6.5mm.
