### ISSUE TITLE
Possible error on the RGB jumpers table

### ISSUE THREAD

**Issue by killmaster** [josefadamcik/SofleKeyboard#77]
Hi,

I was building my Sofle RGB and have a doubt on the jumpers to short to have all the lighting modes on.

Atm the table shows `| Y | Y	| Y | 2-3 | 2-3	|     |`, shouldn't it be `| Y | Y	| Y | 2-3 | 2-3	| 1-2    |`?

Thanks.

**Comment by DaneEvans** [comment]
verified and fixed
