### ISSUE TITLE
RGB top for lasercutting acrylic frame?

### ISSUE THREAD

**Issue by kimipsen** [josefadamcik/SofleKeyboard#78]
@DaneEvans  Are there any plans for adding an image-version of the top for the rgb version, that may be used in lasercutting? I know theres one for the oled/mcu cover.

**Comment by DaneEvans** [comment]
No, although I'd happily do it if someone wants to ship me one.  

No-one is doing laser cuts at a vaguely civilised price in Australia, and all the US companies want an arm and a leg for shipping.  

It would be easy to do, but it's not worth it for me.

**Comment by DaneEvans** [comment]
duplicat of #74
