### ISSUE TITLE
Flashing instructions are outdated

### ISSUE THREAD

**Issue by CGMossa** [josefadamcik/SofleKeyboard#80]
I'mma recent adopter of split-keyboard life.

The instructions on the build guide regarding flashing the board is somewhat outdated.

```
qmk flash -kb sofle/rev1 -km default
```
I don't know what the `make` refers to, as there are no folders mentioned in the build-guide that would point to a instructions.

I'm yet to figure out how to enact changes, but maybe this section could be updated in time for v3?

**Comment by josefadamcik** [comment]
Thank for letting me know. `make` is a command that was used to build & flash the source files some time ago. QMK is moving forward quickly, so things change. I'll adjust that soon.
