### ISSUE TITLE
LED 9 isn't working (drop lighting + per key lighting)

### ISSUE THREAD

**Issue by DLopezGo90** [josefadamcik/SofleKeyboard#82]
LED 8 is working but not LED 9. I don't know what's happening

![image](https://user-images.githubusercontent.com/59780264/119569584-ecb7e080-bd7c-11eb-8f80-b0a009dd5ddc.png)

For your information I made this bridge (J6) because I don't want Indicator LED

![image](https://user-images.githubusercontent.com/59780264/119569896-62bc4780-bd7d-11eb-8f94-869275e708da.png)

Help please

**Comment by DaneEvans** [comment]
Replace 8.
If you cook them, sometimes it's the output that dies.

**Comment by DLopezGo90** [comment]
It didn't work. I replaced LED 8 and 9 and nothing happened

My solder skill isn't bad. I have soldered many Corne Keyboards

You sure LED 9 comes after LED 8? You sure sure they are connected?  DOUT pin goes with silkscreen mark right? Because that's what I did

DOUT is elbow shaped:

![image](https://user-images.githubusercontent.com/59780264/119636463-a8f7c200-bde2-11eb-8ea6-da8a74d44b47.png)

You can see I soldered the elbow shaped contact of the LED to the silkscreen pad on the PCB:

![image](https://user-images.githubusercontent.com/59780264/119637074-46eb8c80-bde3-11eb-95a3-642cdd4f1444.png)

![image](https://user-images.githubusercontent.com/59780264/119637301-8619dd80-bde3-11eb-8afa-ef1f7ca5c972.png)

I have the version with te unconnected via for NET34 and I had to the bridge on the front side to make LEDs 6 and 7 work:

![image](https://user-images.githubusercontent.com/59780264/119637907-2243e480-bde4-11eb-8d0c-50f5158802d2.png)

**Comment by DaneEvans** [comment]
Then I'd make sure that you have the later LEDs enabled and doing
something.

There are no other known board issues. Plenty of user ones though

**Comment by DLopezGo90** [comment]
Should I solder later LEDs? will LED 10 work if 9 doesn't?

**Comment by DLopezGo90** [comment]
Bro I found out what was the issue 

This is the config.h file of sofle keyboard via keymap:

![image](https://user-images.githubusercontent.com/59780264/119658804-8b832200-bdfb-11eb-8f69-115775a4dd73.png)

It will only make 14 LEDs work (7 on each half). It needs to be modified to 72 I think (36 on each half):

![image](https://user-images.githubusercontent.com/59780264/119659053-cd13cd00-bdfb-11eb-9163-6c881decb9ce.png)

This should be added to the build guide?

**Comment by DaneEvans** [comment]
The default one has them all enabled. I don't know where you pulled that
file from, but it's not one of the ones I've released.

**Comment by DLopezGo90** [comment]
Bro where I find the ones you have released?

**Comment by DaneEvans** [comment]
Eventually the QMK repo, once I make it through their review process,  but
for the moment, the master or upstream branches, or any tagged commit on my
fork of qmk.

**Comment by t321** [comment]
As you said @DLopezGo90, only the led until 9 works if you use the via hex, in the readme says that only underglow is enabled (https://github.com/qmk/qmk_firmware/tree/master/keyboards/sofle/keymaps/via).. I also flashed VIA and had the same issue. 

If you install qmk and compile with `qmk compile -kb sofle -km rgb_default` and flash this hex, you will have all the led configured. Don't worry if the leds from the external colums and rows are red, are configured in this way :P
![IMG_20210608_211751](https://user-images.githubusercontent.com/1748893/121574740-dff6e600-ca26-11eb-812d-d98662bfbef9.jpg)

If you want to avoid the compile steps.. you can use the hex that I created (I had to compress in zip because GitHub doesn't allow `*.hex` files): [sofle_rev1_rgb_default.zip](https://github.com/josefadamcik/SofleKeyboard/files/6633459/sofle_rev1_rgb_default.zip)

**Comment by fi0** [comment]
Is there a via firmware that enables all LEDs?

**Comment by DaneEvans** [comment]
No idea.  The only one I have provided is the qmk repo.

Any you compile yourself from the qmk repo from rgb_default, or my keymaps
should have all or most LEDs on by default.

**Comment by fi0** [comment]
@t321 How do I set the outer column to the same colors for the rainbow mood?

**Comment by DaneEvans** [comment]
Remove the outer column from the SET_LAYER_ID macro.

In remove lines 60 and 61

**Comment by fi0** [comment]
@DaneEvans I compiled the rgb_default keymap and found that the last LED didn't light up on both left and right side. 
I've soldered the indicator, per key and underglow LEDs.
