### ISSUE TITLE
Impossible holes

### ISSUE THREAD

**Issue by AlexDaniel** [josefadamcik/SofleKeyboard#9]
There are some holes that are too close to each other, they are almost impossible to be manufactured in a straightforward way.

Example:
![image](https://user-images.githubusercontent.com/5507503/91506698-651b6f00-e8db-11ea-9767-04994ed10437.png)

I checked the production files from JLCPCB and it seems like one of the holes is drilled while the other one is milled. That said, the result is still far from being good:

![20200828_030852_375877101](https://user-images.githubusercontent.com/5507503/91507044-6bf6b180-e8dc-11ea-9ba1-6baa86d9eec9.jpg)

Notice how sometimes there's a bridge between the holes that didn't break away at all. Other times the board has some whiskers left over.

**Comment by josefadamcik** [comment]
As many others this is inherited issue from Lilly58 pro. I have no Idea how this could be fixed while still having a double sided PCB an support fox both MX and Choc switch sockets. 
 
So far I have dropped support for Choc from the next version, but I think the socket making the most trouble here is the MX one so no clean solution there. It might happen that some future version will drop the double-sided pcb concept (once I move controller to the PCB it might be handy to have a 2 different PCBs). That would solve the problem for sure.

**Comment by AlexDaniel** [comment]
> So far I have dropped support for Choc from the next version, but I think the socket making the most trouble here is the MX one so no clean solution there. It might happen that some future version will drop the double-sided pcb concept (once I move controller to the PCB it might be handy to have a 2 different PCBs). That would solve the problem for sure.

Actually, both of these things is what made it a no-brainer for me to choose Sofle. I'm relatively sure that my next keyboard (if I ever make one) will use Choc switches.

One way of fixing the issue is to use the outline layer for both of the holes. For example, JLCPCB already moves one of the holes to the outline layer, so I doubt there's any disadvantage to move both of them. But there is an advantage, because the mill will cut both holes in one continuous move.

**Comment by josefadamcik** [comment]
@AlexDaniel 

> Actually, both of these things is what made it a no-brainer for me to choose Sofle. I'm relatively sure that my next keyboard (if I ever make one) will use Choc switches.

Good to know. To be honest I would be the happiest if I had some kind of script that would fill in footprints for switches (type, socket yes/no, rgb led yes/no) and routing for the board so it could be configured and generated as anyone wishes. Everybody has a bit different preferences.

But I don't believe I would ever have time for something like that. 

> One way of fixing the issue is to use the edge cut layer for both of the holes. For example, JLCPCB already moves one of the holes to the edge cut layer, so I doubt there's any disadvantage to move both of them. But there is an advantage, because the mill will cut both holes in one continuous move.

Good Idea, I have noted it down and try to experiment with this in the future.

**Comment by AlexDaniel** [comment]
Just to illustrate, here's a screenshot of jlcpcb prod files:

![image](https://user-images.githubusercontent.com/5507503/92380492-efe93e80-f111-11ea-93cd-6d1b67c76361.png)

I wonder if kicad footprints can include edge cut drawings. If so, then it's probably the way to do it.

> To be honest I would be the happiest if I had some kind of script that would fill in footprints for switches

Interesting idea. Now that I think about it, it is actually not as hard as it sounds. I [have experimented](https://github.com/RGVID-EU/Butterboard) with generating entire PCBs via kicad api, but that is not needed in this case. Basically, what's needed is a slightly bigger generic footprint that has pads where the traces would connect. Then, each socket-specific footprint can include the required holes, pads *and also* traces that connect its pads to the pads of a generic footprint. This way you'd be able to swap socket types without having to reroute any traces on the board.
