### ISSUE TITLE
Sofle RGB firmware

### ISSUE THREAD

**Issue by fi0** [josefadamcik/SofleKeyboard#93]
I tried rgb_default but the last LED didnt ligth up

Is there an example for using Indicator + backlight + per key lighting?
should it be 72 LEDs instead of 70?

**Comment by DaneEvans** [comment]
Probably. Have you tried it?

**Comment by fi0** [comment]
If I set it to 72, the last LED light up. But some LEDs are red, others are rainbow mood. Probably I need to change the matrix configuration.

**Comment by DaneEvans** [comment]
So it's doing exactly what it's being told to do?

Maybe you should figure out what the firmware is doing, and what you want
it to do, and make the two match?
